export type MarutiHyperlocalNormalizedStatus =
  | 'RECEIVED'
  | 'IN_PROGRESS'
  | 'READY_FOR_DELIVERY'
  | 'ARRIVED_FOR_PICKUP'
  | 'PICKED_UP'
  | 'ARRIVED'
  | 'OUT_FOR_DELIVERY'
  | 'DELIVERED'
  | 'CANCELLED_BY_SHIPPER'
  | 'CANCELLED_BY_CUSTOMER'
  | 'RTO_INITIATED'
  | 'RTO';

export const MARUTI_HYPERLOCAL_STATUS_MAP: Record<
  string,
  MarutiHyperlocalNormalizedStatus
> = {
  RECEIVED: 'RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  ARRIVED_FOR_PICKUP: 'ARRIVED_FOR_PICKUP',
  PICKED_UP: 'PICKED_UP',
  ARRIVED: 'ARRIVED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED_BY_SHIPPER: 'CANCELLED_BY_SHIPPER',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  RTO_INITIATED: 'RTO_INITIATED',
  RTO: 'RTO',
};