export type MarutiNormalizedStatus =
  | 'NEW'
  | 'IN_PROCESS'
  | 'ON_HOLD'
  | 'CANCELED'
  | 'READY_FOR_DISPATCH'
  | 'OUT_FOR_PICKUP'
  | 'NOT_PICKED_UP'
  | 'PICKED_UP'
  | 'IN_TRANSIT'
  | 'OUT_FOR_DELIVERY'
  | 'DELIVERED'
  | 'UNDELIVERED'
  | 'RTO'
  | 'RTO_IN_TRANSIT'
  | 'RTO_OUT_FOR_DELIVERY'
  | 'RTO_DELIVERED';

export const MARUTI_STATUS_MAP: Record<string, MarutiNormalizedStatus> = {
  NEW: 'NEW',
  IN_PROCESS: 'IN_PROCESS',
  ON_HOLD: 'ON_HOLD',
  CANCELED: 'CANCELED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  OUT_FOR_PICKUP: 'OUT_FOR_PICKUP',
  NOT_PICKED_UP: 'NOT_PICKED_UP',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  UNDELIVERED: 'UNDELIVERED',
  RTO: 'RTO',
  RTO_IN_TRANSIT: 'RTO_IN_TRANSIT',
  RTO_OUT_FOR_DELIVERY: 'RTO_OUT_FOR_DELIVERY',
  RTO_DELIVERED: 'RTO_DELIVERED',
};